[Distribution]
Distribution=debian
Release=bookworm

[Output]
#Format=disk
Format=directory
ImageId=NorixOS
OutputDirectory=build

[Content]
KernelCommandLine=console=tty1 quiet
Bootable=no
#Bootloader=grub
Packages=
    systemd
    apt
    wget
    sudo
    inetutils-ping
    systemd-sysv
    systemd-boot
    lvm2
#    linux-image-amd64
    initramfs-tools
#    grub-efi-amd64
#    grub-efi-amd64-bin
    bash
    coreutils
    util-linux
#    openssh-server
    nano
    vim
    curl
#    git
[Build]
Incremental=yes
CacheDirectory=.mkosi-cache


