[Distribution]
Distribution=debian
Release=bookworm

[Output]
Format=disk
ImageId=NorixOS
OutputDirectory=build

[Content]
Bootable=yes
Bootloader=grub

Packages=
    systemd
    apt
    wget
    sudo
    inetutils-ping
    systemd-sysv
    linux-image-cloud-amd64
    initramfs-tools
    grub-efi-amd64
    grub-efi-amd64-bin
    bash
    coreutils
    util-linux
#    openssh-server
    nano
    vim
    curl
#    git
[Build]
Incremental=yes
CacheDirectory=.mkosi-cache
